### ISSUE TITLE
Stitch Data: 422 Client Error: Unprocessable Entity for url: https://api.forecastapp.com/assignments

### ISSUE THREAD

**Issue by kevincal** [singer-io/tap-harvest-forecast#15]
Is anyone else experiencing this new issue?  I perhaps thought it was an expired token so I reauthorized but it's still occurring which is blocking our Stitch Data extract.

```
2021-04-06 13:27:30,991Z   main - INFO Running tap-harvest-forecast version 1.1.0 and target-stitch version 3.2.0
2021-04-06 13:27:31,129Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobStarted ), use_ssl( true )
2021-04-06 13:27:31,131Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobFinished ), use_ssl( true )
2021-04-06 13:27:31,132Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.streamRecordCount ), use_ssl( true )
2021-04-06 13:27:31,204Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobStarted [26] at offset None
2021-04-06 13:27:31,206Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-harvest-forecast --config /tmp/tap_discover_config.json --discover
2021-04-06 13:27:31,436Z    tap - INFO Refreshing access token
2021-04-06 13:27:31,619Z    tap - INFO Got refreshed access token
2021-04-06 13:27:31,648Z   main - INFO Tap exited normally.
2021-04-06 13:27:31,649Z   main - INFO Saving list of discovered streams
2021-04-06 13:27:31,712Z   main - INFO Saving structure of stream assignments (tap_stream_id: assignments)
2021-04-06 13:27:31,729Z   main - INFO Saving structure of stream clients (tap_stream_id: clients)
2021-04-06 13:27:31,745Z   main - INFO Saving structure of stream milestones (tap_stream_id: milestones)
2021-04-06 13:27:31,765Z   main - INFO Saving structure of stream people (tap_stream_id: people)
2021-04-06 13:27:31,786Z   main - INFO Saving structure of stream projects (tap_stream_id: projects)
2021-04-06 13:27:31,797Z   main - INFO Saving structure of stream placeholders (tap_stream_id: placeholders)
2021-04-06 13:27:31,812Z   main - INFO Saving structure of stream roles (tap_stream_id: roles)
2021-04-06 13:27:31,823Z   main - INFO Writing catalog to file
2021-04-06 13:27:31,829Z   main - INFO Selected fields for stream milestones: id, name, updated_at, project_id, date, updated_by_id
2021-04-06 13:27:31,829Z   main - INFO Selected fields for stream assignments: updated_at, start_date, notes, active_on_days_off, updated_by_id, placeholder_id, id, project_id, end_date, person_id, allocation, repeated_assignment_set_id
2021-04-06 13:27:31,829Z   main - INFO Selected fields for stream people: admin, email, updated_at, personal_feed_token_id, archived, roles, first_name, harvest_user_id, color_blind, updated_by_id, subscribed, id, login, avatar_url, last_name, working_days, weekly_capacity
2021-04-06 13:27:31,829Z   main - INFO Selected fields for stream clients: archived, name, updated_at, id, harvest_id, updated_by_id
2021-04-06 13:27:31,829Z   main - INFO Selected fields for stream placeholders: archived, name, updated_at, id, updated_by_id, roles
2021-04-06 13:27:31,829Z   main - INFO Selected fields for stream projects: archived, updated_at, code, start_date, harvest_id, updated_by_id, client_id, id, name, tags, color, notes, end_date
2021-04-06 13:27:31,833Z   main - INFO Current state: {"milestones": "2021-01-22T15:46:26.652000Z", "assignments": "2021-03-12T15:47:41.836000Z", "projects": "2021-03-12T15:47:41.838000Z", "clients": "2021-01-29T16:41:42.736000Z", "placeholders": "2019-01-01T06:00:00Z", "people": "2021-03-12T15:47:41.839000Z"}
2021-04-06 13:27:31,834Z   main - INFO Starting tap: tap-env/bin/tap-harvest-forecast --config /tmp/tap_config.json --properties /tmp/properties.json --catalog /tmp/catalog.json --state /tmp/tap_state.json
2021-04-06 13:27:31,839Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2021-04-06 13:27:32,053Z    tap - INFO Refreshing access token
2021-04-06 13:27:32,227Z    tap - INFO Got refreshed access token
2021-04-06 13:27:32,227Z    tap - INFO Starting sync
2021-04-06 13:27:32,227Z    tap - INFO GET https://api.forecastapp.com/assignments
2021-04-06 13:27:32,266Z target - INFO Using batch_size_prefernces of {'batch_size_preference': None, 'user_batch_size_preference': None, 'full_table_streams': []}
2021-04-06 13:27:32,429Z    tap - CRITICAL 422 Client Error: Unprocessable Entity for url: https://api.forecastapp.com/assignments
2021-04-06 13:27:32,430Z    tap - Traceback (most recent call last):
2021-04-06 13:27:32,430Z    tap -   File "tap-env/bin/tap-harvest-forecast", line 33, in <module>
2021-04-06 13:27:32,430Z    tap -     sys.exit(load_entry_point('tap-harvest-forecast==1.1.0', 'console_scripts', 'tap-harvest-forecast')())
2021-04-06 13:27:32,430Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest_forecast/__init__.py", line 213, in main
2021-04-06 13:27:32,430Z    tap -     raise exc
2021-04-06 13:27:32,430Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest_forecast/__init__.py", line 210, in main
2021-04-06 13:27:32,430Z    tap -     main_impl()
2021-04-06 13:27:32,430Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest_forecast/__init__.py", line 206, in main_impl
2021-04-06 13:27:32,431Z    tap -     do_sync(args.catalog)
2021-04-06 13:27:32,431Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest_forecast/__init__.py", line 169, in do_sync
2021-04-06 13:27:32,431Z    tap -     sync_endpoint(stream.tap_stream_id, stream.schema.to_dict(), mdata)
2021-04-06 13:27:32,431Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest_forecast/__init__.py", line 145, in sync_endpoint
2021-04-06 13:27:32,431Z    tap -     data = request(url)[endpoint]
2021-04-06 13:27:32,431Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2021-04-06 13:27:32,431Z    tap -     ret = target(*args, **kwargs)
2021-04-06 13:27:32,431Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 62, in wrapper
2021-04-06 13:27:32,431Z    tap -     return func(*args, **kwargs)
2021-04-06 13:27:32,431Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest_forecast/__init__.py", line 128, in request
2021-04-06 13:27:32,431Z    tap -     resp.raise_for_status()
2021-04-06 13:27:32,431Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
2021-04-06 13:27:32,431Z    tap -     raise HTTPError(http_error_msg, response=self)
2021-04-06 13:27:32,431Z    tap - requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.forecastapp.com/assignments
2021-04-06 13:27:32,457Z target - INFO Requests complete, stopping loop
2021-04-06 13:27:32,502Z   main - INFO Target exited normally with status 0
2021-04-06 13:27:33,142Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [6] at offset None
2021-04-06 13:27:33,143Z   main - INFO No tunnel subprocess to tear down
2021-04-06 13:27:33,143Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "422 Client Error: Unprocessable Entity for url: https://api.forecastapp.com/assignments". Target succeeded.
```

**Comment by kevincal** [comment]
#16 captures the breaking changes that the Harvest/Forecast team made to the API that is causing this error.

**Comment by xmnlab** [comment]
@kevincal maybe you can find some information about this here https://github.com/singer-io/tap-harvest-forecast/issues/13

**Comment by kevincal** [comment]
Duplicate to #13
