### ISSUE TITLE
Critical Error via Stitchdata

### ISSUE THREAD

**Issue by danwebb4** [singer-io/tap-harvest-forecast#20]
The fix implemented in #17 resolves the original 422 error, but I am now getting a different error:

'dict' object has no attribute 'replication_keys'

The integration via Stitchdata is still not functioning. I have attached the error logs.
[StitchLogs.txt](https://github.com/singer-io/tap-harvest-forecast/files/6533653/StitchLogs.txt)

**Comment by asaf-erlich** [comment]
```
2021-05-24 15:49:05,899Z    tap - CRITICAL 'dict' object has no attribute 'replication_keys'
2021-05-24 15:49:05,900Z    tap - Traceback (most recent call last):
2021-05-24 15:49:05,900Z    tap -   File "tap-env/bin/tap-harvest-forecast", line 33, in <module>
2021-05-24 15:49:05,900Z    tap -     sys.exit(load_entry_point('tap-harvest-forecast==1.1.1', 'console_scripts', 'tap-harvest-forecast')())
2021-05-24 15:49:05,900Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_harvest_forecast/__init__.py", line 258, in main
2021-05-24 15:49:05,900Z    tap -     raise exc
2021-05-24 15:49:05,900Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_harvest_forecast/__init__.py", line 255, in main
2021-05-24 15:49:05,900Z    tap -     main_impl()
2021-05-24 15:49:05,900Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_harvest_forecast/__init__.py", line 249, in main_impl
2021-05-24 15:49:05,901Z    tap -     do_discover()
2021-05-24 15:49:05,901Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_harvest_forecast/__init__.py", line 225, in do_discover
2021-05-24 15:49:05,901Z    tap -     mdata = metadata.write(mdata, (), 'valid-replication-keys', schema.replication_keys)
2021-05-24 15:49:05,901Z    tap - AttributeError: 'dict' object has no attribute 'replication_keys'
```
Looks like the error happens here: https://github.com/singer-io/tap-harvest-forecast/blob/master/tap_harvest_forecast/__init__.py#L225

**Comment by cdilga** [comment]
Can you post the command used to run this?
I believe it's an issue with the configuration. For e.g. I've had this error when not correctly specifying the `-c config.json` when running. 
See this: https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md#running-singer-with-python

**Comment by danwebb4** [comment]
I am running this using Stitchdata's integration and extraction capabilities. Based on much of the conversation at #13, I think many users run it the same way.

**Comment by xmnlab** [comment]
maybe not related but it seems that the "rec" was used before has been created.
https://github.com/singer-io/tap-harvest-forecast/blob/master/tap_harvest_forecast/__init__.py#L180

**Comment by tadhg** [comment]
I'm also getting the same issue using the Stitch data integration. It seems to be using the latest master branch version (v1.1.2) but this issue is still occurring.

**Comment by mwharton3** [comment]
I'm also getting this error in my own environment

**Comment by danwebb4** [comment]
@asaf-erlich @xmnlab Any updates on a possible resolution to this issue?

**Comment by xmnlab** [comment]
I didn't hit this problem yet .. so not sure a possible approach to fix that

**Comment by asaf-erlich** [comment]
Hello @danwebb4 , I'm no longer working at Stitch. I'm ccing @dmosorast who still does who can better comment on this issue moving forward.

**Comment by dmosorast** [comment]
Hello folks, just circling back here now, seems like I missed the notification in the firehose. Thanks, Asaf for the @, I do have some experience with this tap.

Tonight, I had a bit of extra time, and noticed that the `AttributeError` Asaf mentioned should be rather straightforward to troubleshoot, so I decided to fire up a new Forecast trial and see how far I could take it.

I was able to get it at least bare minimum running and performing at what I could call at a glance "potentially acceptable". Of course, note that I'm not a daily user of Forecast, but am very familiar with Singer patterns and practices, so this runs from a Singer perspective as an incremental sync (except for `roles`, which doesn't have a timestamp to bookmark, but should work fine as-is). So, I must rely on all of you to validate that the data are correct, that fields are there as expected, etc.

Hopefully this will get you into a place where you can do that kind of exploration. Here's the PR, though I'm going to have to wait until the morning to release it so I have time to monitor. https://github.com/singer-io/tap-harvest-forecast/pull/24

**Comment by dmosorast** [comment]
After the 1.1.3 release, I was able to create a connection and run it successfully, so this should be good. Thanks everyone for your interest and patience, and please verify that the data is as expected. Closing this issue.
